/*
 * adcInt.c
 *
 * Created: 10/29/2011 9:25:47 PM
 *  Author: bfc
 */ 

#include "adcInt.h"

void adcAInit(){

	ADCA.CTRLB		|= ADC_FREERUN_bm | ADC_RESOLUTION_12BIT_gc;
	ADCA.PRESCALER	= ADC_PRESCALER_DIV16_gc;
	ADCA.REFCTRL	= ADC_REFSEL_VCC_gc;
	
	ADCA.CH0.INTCTRL = ADC_CH_INTLVL_LO_gc;
//	ADCA.CH1.INTCTRL = ADC_CH_INTLVL_LO_gc;
//	ADCA.CH2.INTCTRL = ADC_CH_INTLVL_LO_gc;
//	ADCA.CH3.INTCTRL = ADC_CH_INTLVL_LO_gc;
	
	ADCA.CH0.MUXCTRL = CHANNEL_0;
	ADCA.CH1.MUXCTRL = CHANNEL_2;
	ADCA.CH2.MUXCTRL = CHANNEL_4;
	ADCA.CH3.MUXCTRL = CHANNEL_6;
	
	ADCA.CH0.CTRL |= ADC_CH_INPUTMODE_SINGLEENDED_gc | ADC_CH_START_bm;
//	ADCA.CH1.CTRL |= ADC_CH_INPUTMODE_SINGLEENDED_gc | ADC_CH_START_bm;
//	ADCA.CH2.CTRL |= ADC_CH_INPUTMODE_SINGLEENDED_gc | ADC_CH_START_bm;
//	ADCA.CH3.CTRL |= ADC_CH_INPUTMODE_SINGLEENDED_gc | ADC_CH_START_bm;
	
	ADCA.CTRLA	   = ADC_ENABLE_bm | ADC_CH0START_bm | ADC_CH0START_bm | ADC_CH0START_bm | ADC_CH0START_bm; //start all the things	
	PMIC.CTRL	  |= PMIC_LOLVLEN_bm | PMIC_RREN_bm;
}

ISR(ADCA_CH0_vect){
	ADCA.CH0.MUXCTRL ^=1<<3;
}

ISR(ADCA_CH1_vect){
	ADCA.CH1.MUXCTRL ^=1<<3;
}

ISR(ADCA_CH2_vect){
	ADCA.CH2.MUXCTRL ^=1<<3;
}

ISR(ADCA_CH3_vect){
	ADCA.CH3.MUXCTRL ^=1<<3;
}

